/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package aula14;

/**
 *
 * @author fabiodemo
 */
public class Exercicio_3_botao_incremento_decremento extends javax.swing.JFrame {

    /**
     * Creates new form Exercicio_3_botao_incremento_decremento
     */
    public Exercicio_3_botao_incremento_decremento() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        TextN1 = new javax.swing.JTextField();
        TextN2 = new javax.swing.JTextField();
        LabelN1 = new javax.swing.JLabel();
        LabelN2 = new javax.swing.JLabel();
        IncrementaUm = new javax.swing.JButton();
        IncrementaDois = new javax.swing.JButton();
        DecrementaUm = new javax.swing.JButton();
        DecrementaDois = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Incrementar ou decrementar dois números");

        TextN1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextN1ActionPerformed(evt);
            }
        });

        TextN2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextN2ActionPerformed(evt);
            }
        });

        LabelN1.setText("Número 1:");

        LabelN2.setText("Número 2:");

        IncrementaUm.setText("+");
        IncrementaUm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IncrementaUmActionPerformed(evt);
            }
        });

        IncrementaDois.setText("+");
        IncrementaDois.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IncrementaDoisActionPerformed(evt);
            }
        });

        DecrementaUm.setText("-");
        DecrementaUm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DecrementaUmActionPerformed(evt);
            }
        });

        DecrementaDois.setText("-");
        DecrementaDois.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DecrementaDoisActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Ubuntu", 0, 20)); // NOI18N
        jLabel1.setText("Incrementa ou Decrementa:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(58, 58, 58)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(LabelN1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(TextN1))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(LabelN2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(TextN2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(IncrementaDois)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(DecrementaDois, javax.swing.GroupLayout.DEFAULT_SIZE, 31, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(IncrementaUm)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(DecrementaUm, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1)))
                .addContainerGap(130, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TextN1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LabelN1)
                    .addComponent(IncrementaUm)
                    .addComponent(DecrementaUm))
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TextN2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LabelN2)
                    .addComponent(IncrementaDois)
                    .addComponent(DecrementaDois))
                .addContainerGap(152, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void TextN1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextN1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TextN1ActionPerformed

    private void TextN2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextN2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TextN2ActionPerformed

    private void IncrementaUmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IncrementaUmActionPerformed
        int value = Integer.parseInt(TextN1.getText());
        value += 1;
        TextN1.setText(Integer.toString(value));
    }//GEN-LAST:event_IncrementaUmActionPerformed

    private void IncrementaDoisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IncrementaDoisActionPerformed
        int value = Integer.parseInt(TextN2.getText());
        value += 1;
        TextN2.setText(Integer.toString(value));
    }//GEN-LAST:event_IncrementaDoisActionPerformed

    private void DecrementaUmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DecrementaUmActionPerformed
        int value = Integer.parseInt(TextN1.getText());
        value -= 1;
        TextN1.setText(Integer.toString(value));
    }//GEN-LAST:event_DecrementaUmActionPerformed

    private void DecrementaDoisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DecrementaDoisActionPerformed
        int value = Integer.parseInt(TextN2.getText());
        value -= 1;
        TextN2.setText(Integer.toString(value));
    }//GEN-LAST:event_DecrementaDoisActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Exercicio_3_botao_incremento_decremento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Exercicio_3_botao_incremento_decremento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Exercicio_3_botao_incremento_decremento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Exercicio_3_botao_incremento_decremento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new Exercicio_3_botao_incremento_decremento().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton DecrementaDois;
    private javax.swing.JButton DecrementaUm;
    private javax.swing.JButton IncrementaDois;
    private javax.swing.JButton IncrementaUm;
    private javax.swing.JLabel LabelN1;
    private javax.swing.JLabel LabelN2;
    private javax.swing.JTextField TextN1;
    private javax.swing.JTextField TextN2;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
