/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package aula18;

import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;

/**
 *
 * @author fabiodemo
 */
public class ExercicioIIDoisCamposJList extends javax.swing.JFrame {
    DefaultListModel listmodel1 = new  DefaultListModel();
    DefaultListModel listmodel2 = new  DefaultListModel();
    /**
     * Creates new form ExercicioIIDoisCamposJList
     */
    public ExercicioIIDoisCamposJList() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        Lista2 = new javax.swing.JList<>();
        jScrollPane2 = new javax.swing.JScrollPane();
        Lista1 = new javax.swing.JList<>();
        SendToL1 = new javax.swing.JButton();
        SendToL2 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        TextField1 = new javax.swing.JTextField();
        TextField2 = new javax.swing.JTextField();
        OkLista2 = new javax.swing.JButton();
        OkLista1 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        ResetLista1 = new javax.swing.JButton();
        ResetLista2 = new javax.swing.JButton();
        LimpaLista1 = new javax.swing.JButton();
        LimpaLista2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jScrollPane1.setViewportView(Lista2);

        jScrollPane2.setViewportView(Lista1);

        SendToL1.setText("<-------------- Enviar item");
        SendToL1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SendToL1ActionPerformed(evt);
            }
        });

        SendToL2.setText(" Enviar item ------------>");
        SendToL2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SendToL2ActionPerformed(evt);
            }
        });

        jLabel1.setText("Lista 1:");

        jLabel2.setText("Lista 2:");

        OkLista2.setText("OK");
        OkLista2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OkLista2ActionPerformed(evt);
            }
        });

        OkLista1.setText("OK");
        OkLista1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OkLista1ActionPerformed(evt);
            }
        });

        jLabel3.setText("Lista 2");

        jLabel4.setText("Lista 1");

        ResetLista1.setText("Reset");
        ResetLista1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ResetLista1ActionPerformed(evt);
            }
        });

        ResetLista2.setText("Reset");
        ResetLista2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ResetLista2ActionPerformed(evt);
            }
        });

        LimpaLista1.setText("Limpa a Lista 1");
        LimpaLista1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LimpaLista1ActionPerformed(evt);
            }
        });

        LimpaLista2.setText("Limpa a Lista 2");
        LimpaLista2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LimpaLista2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(82, 82, 82)
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(LimpaLista1)
                                        .addGap(0, 0, Short.MAX_VALUE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(0, 0, Short.MAX_VALUE)
                                        .addComponent(LimpaLista2))
                                    .addComponent(SendToL1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(SendToL2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(TextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(ResetLista1)
                                .addGap(3, 3, 3)
                                .addComponent(OkLista1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel2)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(133, 133, 133)
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(TextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(ResetLista2))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(48, 48, 48)))
                        .addComponent(OkLista2)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(139, 139, 139))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(TextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(OkLista1)
                    .addComponent(TextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(OkLista2)
                    .addComponent(ResetLista1)
                    .addComponent(ResetLista2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 92, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addContainerGap())
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addComponent(SendToL2)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(SendToL1)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(LimpaLista1)
                            .addGap(22, 22, 22)
                            .addComponent(LimpaLista2)
                            .addGap(26, 26, 26)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ResetLista1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ResetLista1ActionPerformed
        TextField1.setText("");
    }//GEN-LAST:event_ResetLista1ActionPerformed

    private void ResetLista2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ResetLista2ActionPerformed
        TextField2.setText("");
    }//GEN-LAST:event_ResetLista2ActionPerformed

    private void OkLista1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OkLista1ActionPerformed
        if("".equals(TextField1.getText())){
            JOptionPane.showMessageDialog(null, "Inserir texto antes de adicioná-lo à Lista 1!");
        }
        else{
            Lista1.setModel(listmodel1);
            listmodel1.addElement(TextField1.getText());
        }
    }//GEN-LAST:event_OkLista1ActionPerformed

    private void OkLista2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OkLista2ActionPerformed
        if("".equals(TextField2.getText())){
            JOptionPane.showMessageDialog(null, "Inserir texto antes de adicioná-lo à Lista 2!");
        }
        else{
            Lista2.setModel(listmodel2);
            listmodel2.addElement(TextField2.getText());
        }
    }//GEN-LAST:event_OkLista2ActionPerformed

    private void LimpaLista1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LimpaLista1ActionPerformed
        listmodel1.removeAllElements();
    }//GEN-LAST:event_LimpaLista1ActionPerformed

    private void LimpaLista2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LimpaLista2ActionPerformed
        listmodel2.removeAllElements();
    }//GEN-LAST:event_LimpaLista2ActionPerformed

    private void SendToL2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SendToL2ActionPerformed
        if(Lista1.isSelectionEmpty()){
            JOptionPane.showMessageDialog(null, "Selecionar item antes de enviá-lo à Lista 2!");
        }
        else{
            Lista2.setModel(listmodel2);
            listmodel2.addElement(Lista1.getSelectedValue());
        }
    }//GEN-LAST:event_SendToL2ActionPerformed

    private void SendToL1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SendToL1ActionPerformed
        if(Lista1.isSelectionEmpty()){
            JOptionPane.showMessageDialog(null, "Selecionar item antes de enviá-lo à Lista 1!");
        }
        else{
            Lista1.setModel(listmodel1);
            listmodel1.addElement(Lista2.getSelectedValue());
        }
    }//GEN-LAST:event_SendToL1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ExercicioIIDoisCamposJList.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ExercicioIIDoisCamposJList.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ExercicioIIDoisCamposJList.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ExercicioIIDoisCamposJList.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new ExercicioIIDoisCamposJList().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton LimpaLista1;
    private javax.swing.JButton LimpaLista2;
    private javax.swing.JList<String> Lista1;
    private javax.swing.JList<String> Lista2;
    private javax.swing.JButton OkLista1;
    private javax.swing.JButton OkLista2;
    private javax.swing.JButton ResetLista1;
    private javax.swing.JButton ResetLista2;
    private javax.swing.JButton SendToL1;
    private javax.swing.JButton SendToL2;
    private javax.swing.JTextField TextField1;
    private javax.swing.JTextField TextField2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    // End of variables declaration//GEN-END:variables
}
